---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cluster-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        DOMAIN: "{{ .DOMAIN }}"
        TIMEZONE: "{{ .TIMEZONE }}"
        LATITUDE: "{{ LATITUDE }}"
        LONGITUDE: "{{ LONGITUDE }}"
  dataFrom:
    - extract:
        key: homelab-cluster-settings
