---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
spec:
  interval: 30m
  chart:
    spec:
      chart: dependency-track
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: dependency-track
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ingress:
      enabled: true
      hostname: depcheck.altena.io
      ingressClassName: internal
