# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.0
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.0

clusterName: "olympus"
endpoint: https://192.168.2.101:6443
clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"
additionalApiServerCertSans: &sans
  - "192.168.2.101"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "artemis"
    ipAddress: "192.168.2.102"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:c2:a0:f3"
        dhcp: false
        addresses:
          - "192.168.2.102/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.2.254"
        mtu: 1500
        vip:
          ip: "192.168.2.101"
  - hostname: "apollo"
    ipAddress: "192.168.2.103"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:89:47:67"
        dhcp: false
        addresses:
          - "192.168.2.103/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.2.254"
        mtu: 1500
        vip:
          ip: "192.168.2.101"
  - hostname: "athena"
    ipAddress: "192.168.2.104"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:cb:45:6a"
        dhcp: false
        addresses:
          - "192.168.2.104/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.2.254"
        mtu: 1500
        vip:
          ip: "192.168.2.101"

# Global patches
patches:
  - # Force nameserver
    |-
    machine:
      network:
        nameservers:
          - 192.168.2.111
  - # Configure NTP
    |-
    machine:
      time:
        disabled: false
        servers:
          - time.cloudflare.com
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/containerd.yaml"
  - "@./patches/global/disable-search-domain.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/openebs-local.yaml"
  - "@./patches/global/sysctl.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"
    - "@./patches/controller/etcd.yaml"
