---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 50Gi
