---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            delay: 30,
            duplicateCategories: false,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDirs: [
              "/media/Downloads/qbittorrent/complete/cross-seed"
            ],
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://qbittorrent.downloads.svc.cluster.local:8080",
            radarr: [
              "http://radarr.downloads.svc.cluster.local:7878/?apikey={{ .RADARR_API_KEY }}"
            ],
            skipRecheck: true,
            sonarr: [
              "http://sonarr.downloads.svc.cluster.local:8989/?apikey={{ .SONARR_API_KEY }}"
            ],
            torznab: [],
            // torznab: [
            //     88, // HUNO
            //     89, // OTW
            //     90, // FNP
            // ].map(i => `http://prowlarr.downloads.svc.cluster.local/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
            useClientTorrents: true
          };
  dataFrom:
    - extract:
        key: cross-seed-secret
    - extract:
        key: radarr-secret
    - extract:
        key: sonarr-secret
    - extract:
        key: prowlarr-secret
