---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  # - ./snapshot-controller/ks.yaml
components:
  - ../../components/common
