---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-github
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-github
    creationPolicy: Owner
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_PERSONAL_ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: toolhive
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-garmin-email
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-garmin-email
    creationPolicy: Owner
    template:
      data:
        GARMIN_EMAIL: "{{ .GARMIN_EMAIL }}"
  dataFrom:
    - extract:
        key: toolhive
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-garmin-password
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-garmin-password
    creationPolicy: Owner
    template:
      data:
        GARMIN_PASSWORD: "{{ .GARMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: toolhive
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-hass
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-hass
    creationPolicy: Owner
    template:
      data:
        HA_TOKEN: "{{ .HA_TOKEN }}"
  dataFrom:
    - extract:
        key: toolhive
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-unifi-username
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-unifi-username
    creationPolicy: Owner
    template:
      data:
        UNIFI_USERNAME: "{{ .UNIFI_USERNAME }}"
  dataFrom:
    - extract:
        key: toolhive
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-unifi-password
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: toolhive-unifi-password
    creationPolicy: Owner
    template:
      data:
        UNIFI_PASSWORD: "{{ .UNIFI_PASSWORD }}"
  dataFrom:
    - extract:
        key: toolhive
