---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./cilium-l2/ks.yaml
  - ./reloader/ks.yaml
