---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: bootstrap/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/infrastructure:
  - changed-files:
      - any-glob-to-any-file: infrastructure/**/*
area/mise:
  - changed-files:
      - any-glob-to-any-file: .mise.toml
