[env]
KUBERNETES_DIR = '{{config_root}}/kubernetes'
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
TALOSCONFIG = '{{config_root}}/talos/clusterconfig/talosconfig'
