---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1yrzd67uvapjjawwjgfc7drkyu8pk2m800w4knjzrg69jxkm0afcqnr9qfz"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1yrzd67uvapjjawwjgfc7drkyu8pk2m800w4knjzrg69jxkm0afcqnr9qfz"
