---
creation_rules:
  - # phobos cluster (society)
    path_regex: kubernetes/clusters/phobos/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1rk7l90pf4vavjlkxzf5v678fj9g5l09ar7wz9kj2v5q5la4fapeqvc38vk"
  - # fallback for any other sops file in the repo
    path_regex: .*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1rk7l90pf4vavjlkxzf5v678fj9g5l09ar7wz9kj2v5q5la4fapeqvc38vk"
