[env]
MINIJINJA_CONFIG_FILE = '{{config_root}}/.minijinja.toml'
KUBECONFIG = '{{config_root}}/kubernetes/kubeconfig'
TALOSCONFIG = '{{config_root}}/kubernetes/talos/clusterconfig/talosconfig'
TASK_X_ENV_PRECEDENCE = 1
TASK_X_MAP_VARIABLES = 0

[tools]
"aqua:astral-sh/uv" = ["latest"]
"pipx:flux-local" = ["7.0.0"]
