---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - pipefail
shopt:
  - globstar

includes:
  flux: .taskfiles/flux/Taskfile.yaml
  kubernetes: .taskfiles/kubernetes/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  NIXOS_DIR: "{{.ROOT_DIR}}/nixos"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"

tasks:
  default:
    silent: true
    cmd: task --list

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
