---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - pipefail
shopt:
  - globstar

includes:
  flux: .taskfiles/flux/Taskfile.yaml
  kubernetes: .taskfiles/kubernetes/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml
  talos: .taskfiles/talos/Taskfile.yaml

vars:
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/kubernetes/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  TALOSCONFIG: "talos/clusterconfig/talosconfig"
  TALHELPER_CLUSTER_DIR: "talos/clusterconfig"
  TALHELPER_SECRET_FILE: "talos/talsecret.sops.yaml"
  TALHELPER_CONFIG_FILE: "talos/talconfig.yaml"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"
  TALOSCONFIG: "{{.TALOSCONFIG}}"
  MINIJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/.minijinja.toml"

tasks:
  default:
    silent: true
    cmd: task --list

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
