---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - pipefail
shopt:
  - globstar

includes:
  flux: .taskfiles/flux/Taskfile.yaml
  kubernetes: .taskfiles/kubernetes/Taskfile.yaml
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  sops: .taskfiles/sops/Taskfile.yaml
  talos: .taskfiles/talos/Taskfile.yaml

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubeconfig"
  MINIJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/.minijinja.toml"
  TALOSCONFIG: "{{.KUBERNETES_DIR}}/talos/clusterconfig/talosconfig"

env:
  KUBECONFIG: "{{.KUBECONFIG}}"
  MINIJINJA_CONFIG_FILE: "{{.MINIJINJA_CONFIG_FILE}}"
  TALOSCONFIG: "{{.TALOSCONFIG}}"

tasks:
  default:
    silent: true
    cmd: task --list

  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
