apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-finance
spec:
  ingressClassName: internal
  rules:
  - host: actual.altena.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actual
            port:
              name: web
  tls:
  - hosts:
    - actual.altena.io
    secretName: altena-io-tls
