---
apiVersion: v1
kind: Service
metadata:
  name: actual
  labels:
    app: actual
spec:
  selector:
    app: actual
  ports:
    - name: http
      port: 5006
      targetPort: 5006
      protocol: TCP
  type: ClusterIP
