apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name forgejo-runner
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: onepassword-connect
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          FORGEJO_INSTANCE_URL: "{{ .FORGEJO_INSTANCE_URL }}"
          RUNNER_TOKEN: "{{ .RUNNER_TOKEN }}"
    dataFrom:
      - extract:
          key: *name
