---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-marja
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-marja
    creationPolicy: Owner
    template:
      data:
        LITELLM_API_KEY: "{{ .api_key }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
  dataFrom:
    - extract:
        key: hermes-marja
