apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
spec:
  template:
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --dns-name=external-secrets-webhook.security.svc
