apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wekan
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      wekan:
        containers:
          app:
            image:
              repository: ghcr.io/wekan/wekan
              tag: v7.88
            env:
              - name: ROOT_URL
                value: https://kanban.altena.io
              - name: MONGO_URL
                valueFrom:
                  secretKeyRef:
                    name: wekan-env
                    key: MONGO_URL
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 2Gi
          mongodb:
            image:
              repository: docker.io/library/mongo
              tag: 4.4
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: wekan-env
                    key: MONGO_INITDB_ROOT_USERNAME
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: wekan-env
                    key: MONGO_INITDB_ROOT_PASSWORD
              - name: MONGO_INITDB_DATABASE
                valueFrom:
                  secretKeyRef:
                    name: wekan-env
                    key: MONGO_INITDB_DATABASE
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000

    persistence:
      wekan:
        enabled: true
        existingClaim: wekan
        advancedMounts:
          wekan:
            app:
              - path: /data
            mongodb:
              - path: /data/db
    service:
      app:
        controller: wekan
        ports:
          http:
            port: 3001

    route:
      app:
        hostnames:
          - kanban.altena.io
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: wekan
                port: 3001
