---
# Separate PVC manifest
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wekan
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi-sc
