apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:QHNEC0WYG2rSx3qjWO4eaQMTy+0doIP8Diifi200whwRGBZCzBKi6fCLeQIcmlqDA9qVuvuaTtexb5W0FTWPmiPpzGsqoG1IJ0P24aA=,iv:5MoX/DLeOkZQmnxbEiuvDgjKDorMQXXX8O/op7EaAbE=,tag:TK+BGbYvMeQBXozjZ2b/Dw==,type:comment]
    #ENC[AES256_GCM,data:iQgnFsdVky0eCebMbFAF+G6f08hgSxzJCc0mZ/Bl+a4h7RtqfdbKp4GnFEvvUq+ICPioClb1VwAU7cUNWGTEGFHjBpGOth56,iv:xtWe6FHZtXRWmU5iePd10aNmryukbtmvVzSWEOSHyqA=,tag:oaWdUxmtvbs8g0XtElUFsw==,type:comment]
    NFS_SERVER_ADDRESS: ENC[AES256_GCM,data:gdT4/RtUVvJ3nJ6A9A==,iv:2LYdLBaZka+Txsuk/cwgPkUsk8CVU+guGqSCSIPWPTY=,tag:M/b3ddRRgkndygzaZAqYGw==,type:str]
    NFS_SERVER_PATH: ENC[AES256_GCM,data:ewm+20WGuiEylaMqvCYitY4=,iv:ZGRKkBrbngvqZGe+a3cZWqftUQxR0pw3WYvMeHhLDUE=,tag:oAb+npTlr4PqFcrUfxDtyA==,type:str]
sops:
    age:
        - recipient: age1rk7l90pf4vavjlkxzf5v678fj9g5l09ar7wz9kj2v5q5la4fapeqvc38vk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR0wwcEhlcDZ1UVE1TEJ4
            SVpaN3JSWVc2dTNKeU9vWHhPQXlWdEFLM3h3Ck5tckJVenp2WXhiUFVjQ1hsMHR3
            Y0xTMmhUUEVxem5oc1V2ZVI0TlBCTWcKLS0tIGZjb2tuUkhGSEY3bnAyNGtMY2F0
            L29SL3g0Mm9QNG5KMkM1ZzVzanpUdjAKAgP/aHEAPjMZuW11I2UqEsu4g+QNCbcy
            f2y97bJOAutC6nm+kVGLZvi6IgETNetCTZIIiBg29Ihuhl56WguoAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T10:52:45Z"
    mac: ENC[AES256_GCM,data:+kqPAIgffbv8/r8i7wG+HYlF8LVkxnMWJNssnBePgmVeSThz+Rq6NsfLSHXYaw/F5YwPG6gzDIsa1lp6aY7edRtInT/lmJgt+H82lzRF0ZIvH+ToykNuwnyRn+5gVNk1FRm7vW7AJ/rfwm6il3HwBuO2sMG/BhxXAh9IYr9Gv8E=,iv:Hw10nadUlqnM867zTzCnW2jFLTWOZvmx67XX7PU3y0U=,tag:pyylrm33XIEpA3WWMx/7IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
