apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.10.5
    releaseName: external-secrets
    namespace: external-secrets # Specify the target namespace
    valuesInline:
      # Override default Helm chart values here, if needed
      serviceAccount:
        create: true
      controller:
        logLevel: debug
