---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bookboss-secret
    creationPolicy: Owner
    template:
      data:
        # BookBoss
        BOOKBOSS__DATABASE__DATABASE_URL: "postgres://bookboss:{{ .bookboss_db_password }}@homelab-rw.databases.svc.cluster.local:5432/bookboss"
        BOOKBOSS__ENCRYPTION_SECRET: "{{ .bookboss_encryption_secret }}"
        BOOKBOSS__OIDC__CLIENT_SECRET: "{{ .bookboss_oauth_client_secret }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: bookboss
        INIT_POSTGRES_HOST: homelab-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: bookboss
        INIT_POSTGRES_PASS: "{{ .bookboss_db_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: bookboss
      rewrite:
        - regexp:
            source: "(.*)"
            target: "bookboss_$1"
    - extract:
        key: cloudnative-pg
