---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: "${VOLSYNC_CLAIM:=${APP}}"
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
    copyMethod: Snapshot
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
    moverSecurityContext:
      runAsUser: ${APP_UID:=1000}
      runAsGroup: ${APP_GID:=1000}
      fsGroup: ${APP_GID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /mnt/zfs/kopia
            server: 192.168.1.100
    parallelism: 2
    repository: "${APP}-volsync-secret"
    retain:
      hourly: 24
      daily: 7
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-block}"
