apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  project: networking
  source:
    repoURL: https://github.com/davealtena/argo-homelab
    path: apps/argocd/base/networking
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
