---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm
    creationPolicy: Owner
    template:
      data:
        ANTHROPIC_API_KEY: "{{ .litellm_anthropic_api_key }}"
        OPENAI_API_KEY: "{{ .litellm_openai_api_key }}"
        LITELLM_MASTER_KEY: "{{ .litellm_master_key }}"
        DB_PASSWORD: "{{ .litellm_db_password }}"
        DATABASE_URL: "postgresql://litellm:{{ .litellm_db_password }}@homelab-rw.databases.svc.cluster.local:5432/litellm"
        # Postgres Init
        INIT_POSTGRES_DBNAME: litellm
        INIT_POSTGRES_HOST: homelab-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_PASS: "{{ .litellm_db_password }}"
        INIT_POSTGRES_USER: litellm
  dataFrom:
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "litellm_$1"
    - extract:
        key: cloudnative-pg
