---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: mosquitto
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
  interval: 1h
  path: ./kubernetes/apps/databases/mosquitto/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: databases
  wait: false
  timeout: 5m
  postBuild:
    substitute:
      APP: mosquitto
      VOLSYNC_CLAIM: mosquitto-config
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
