---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns-cloudflare
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.19.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
  # Optional verification - remove if not needed
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/charts-mirror.*$"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns-cloudflare
  install:
    crds: CreateReplace
    disableSchemaValidation: true # Work around schema validation issues
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    disableSchemaValidation: true # Work around schema validation issues
    remediation:
      strategy: rollback
      retries: 3
  values:
    loglevel: info
    fullnameOverride: *app
    provider:
      name: cloudflare
    env:
      - name: &name CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: *name
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --gateway-name=envoy-external
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-cloudflare-secret
    policy: sync
    sources:
      - crd
      - gateway-httproute
    txtOwnerId: main
    txtPrefix: k8s.
    domainFilters: ["altena.io"]
    serviceMonitor:
      enabled: true

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *name
            patch: |-
              - op: add
                path: /spec/template/spec/enableServiceLinks
                value: false
