---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#   # Pre Flux resources
  - ./namespace.yaml
#   # Flux-Kustomizations
  - ./cnpg-operator/ks.yaml
  - ./emqx/ks.yaml
