---
# cleanup-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: multus-cleanup
  annotations:
    kubernetes.io/hook: pre-delete,pre-upgrade
    kubernetes.io/hook-weight: "-5"
    kubernetes.io/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      hostNetwork: true
      containers:
        - name: cleanup
          image: docker.io/library/alpine:3.21
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -x
              rm -rf /host/etc/cni/net.d/*multus*
              rm -rf /host/opt/cni/bin/*multus*
          volumeMounts:
            - name: cni-net-dir
              mountPath: /host/etc/cni/net.d
            - name: cni-bin-dir
              mountPath: /host/opt/cni/bin
      volumes:
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
      restartPolicy: Never
