---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-secrets
    creationPolicy: Owner
    template:
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .esphome_wifi_ssid }}"
          wifi_pwd: "{{ .esphome_wifi_password }}"

          mqtt_host: mqtt.altena.io
          mqtt_user: "{{ .emqx_user_mqtt_username }}"
          mqtt_pwd: "{{ .emqx_user_mqtt_password }}"

          domain_devices: local.altena.io
  dataFrom:
    - extract:
        key: esphome
      rewrite:
        - regexp:
            source: "(.*)"
            target: "esphome_$1"
    - extract:
        key: emqx
      rewrite:
        - regexp:
            source: "(.*)"
            target: "emqx_$1"
