---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
    - name: cnpg-cluster
    - name: kanidm
  components:
    - ../../../../components/kanidm-oauth2
  path: ./kubernetes/apps/selfhosted/mealie/app
  prune: true
  postBuild:
    substitute:
      APP: mealie
      OAUTH2_DISPLAYNAME: Mealie
      OAUTH2_HOST: mealie
      OAUTH2_REDIRECT_PATH: /login
      OAUTH2_GROUP: mealie-users
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
