---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname prowlarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/downloads/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: external-secrets-stores
      namespace: security
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "2000"
      APP_GID: "2000"
      VOLSYNC_CLAIM: prowlarr-config
