version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: d88hqo.23va8dzlyr270eua
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEFxdWIvYnJqeXBwWmNCZzkzOWVaOStNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5UQXhNakl5TURJNU5EbGFGdzB6TlRBeE1qQXlNREk1TkRsYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBRjZ6amNHWmFCa3dyU2pyNVNjc1Y2Zm9xbG1BaXRSdHJNRzhwCll0YmEvd1dqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVVUk5blkrNkZBdEE3UzlKLwpDK08rdGhZc1V2UXdCUVlESzJWd0EwRUFBdXNXbzlMRUgwN1l0M09xRlVsc3N4dHAxV05TOXpjSnJTQnNma3pICmcyTGNGblQ1VVRrRk9kZnI2czF5VldpNVJldG5pNGN6dTR5K0doSktnaUw4RGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJS0lIOStpekNlRkNreTIyYnlsNWt0SnRJa0ZNNTFZTnJNZkIyZFRlQ21lZwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
  certSANs:
    - 192.168.2.101
    - 127.0.0.1
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.32.2
    extraMounts:
      - destination: /var/openebs/local
        type: bind
        source: /var/openebs/local
        options:
          - bind
          - rshared
          - rw
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 192.168.2.0/24
    disableManifestsDirectory: true
  network:
    hostname: odin
    interfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:fd:a1:37
        addresses:
          - 192.168.2.102/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.2.254
        mtu: 1500
        dhcp: false
        vip:
          ip: 192.168.2.101
    nameservers:
      - 192.168.2.111
    disableSearchDomain: true
  install:
    disk: /dev/sda
    extraKernelArgs:
      - i915.enable_guc=3
      - intel_iommu=on
      - iommu=pt
    image: factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30:v1.9.4
    wipe: false
  files:
    - content: |-
        [plugins."io.containerd.grpc.v1.cri"]
          enable_unprivileged_ports = true
          enable_unprivileged_icmp = true
        [plugins."io.containerd.grpc.v1.cri".containerd]
          discard_unpacked_layers = false
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          discard_unpacked_layers = false
      permissions: 0o0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  time:
    disabled: false
    servers:
      - time.cloudflare.com
  sysctls:
    fs.inotify.max_queued_events: "65536"
    fs.inotify.max_user_instances: "8192"
    fs.inotify.max_user_watches: "524288"
    net.core.rmem_max: "2500000"
    net.core.wmem_max: "2500000"
  features:
    rbac: true
    stableHostname: true
    kubernetesTalosAPIAccess:
      enabled: true
      allowedRoles:
        - os:admin
      allowedKubernetesNamespaces:
        - system-upgrade
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
      resolveMemberNames: true
  udev:
    rules:
      - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
  nodeLabels:
    intel.feature.node.kubernetes.io/gpu: "true"
    node.kubernetes.io/exclude-from-external-load-balancers: ""
cluster:
  id: 6VFcgyyrMP43EeXdOXBs-NO_pVdlIbhoD8iVHG6akzc=
  secret: eK6S+73tvU/Z11pWkAnH25tyFbXPTD0U8X05/CMeZNY=
  controlPlane:
    endpoint: https://192.168.2.101:6443
  clusterName: valhalla
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.69.0.0/16
    serviceSubnets:
      - 10.96.0.0/16
  token: 1qwca1.sp3gk4cr3rp9fxbp
  secretboxEncryptionSecret: zyE9jI1TmShxqcXJTnBzXejydgliNtf1/UKyFMlif6o=
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUswMEd4K050NkduTVlscCs4VFJuVjR3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEF4TWpJeU1ESTVORGRhRncwek5UQXhNakF5TURJNQpORGRhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVNqc3I5NE5DcVN3c2FRVlAzeHg3OStPeWgwQzNWZUVGNko2UUpUdjRjUTE2TXl1R1VoTE9RK0twTFYKZ3dGQ2pLbTlsa3RDU01IZTNUZ2RIUjJWTUEzTG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTFhjczNjYUhxWVFWd3NqUkhGTEZLdU4wbWdDTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEdlFZU20KcmNRaWxOUzlWZ1BGQUk2bHpSWHRNb2FxdWNmUGpsdlJ0NS9MMHdJZ2JMMng5NFhwYklWVjJDZDNwelREYUM5dgo1aTBoQWswWkJWWG10c2MzbjFZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUUybEdtUkpoeEMrek44ODVWZmMyTUxHbkpubS9PNHhZY2UvRUYrclBtYjFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbzdLL2VEUXFrc0xHa0ZUOThjZS9manNvZEF0MVhoQmVpZWtDVTcrSEVOZWpNcmhsSVN6awpQaXFTMVlNQlFveXB2WlpMUWtqQjN0MDRIUjBkbFRBTnl3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  aggregatorCA:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFhZ0F3SUJBZ0lSQUxoSzkxZFZiTU9oNCtuZVFNRExYR013Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5UQXhNakl5TURJNU5EZGFGdzB6TlRBeE1qQXlNREk1TkRkYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVJEeXdOMmlIa3NHMTJCVGxXM0tMbWNhaFJoeXUrcGJuN3FvVmNDdk4xNkdpTEVsZ2tmCmVpcjIxYjhNUHJTWHFmemlJMmxJcWJHRjZaZHliTStEOUxyZ28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGR3NseG1MdjVUSGpKYnBFTTUzNzg5UFRWMU1RTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDCklRQ3UxQXpJU1IrcW1iWUp0VCt3MGV2K0N6QzN5cElKY0pHVmFCWEJ1M2NxVlFJZ0s2ME5UMFNkWDdzck9KZUUKTWJoZTViaFdTZWhlTDVtbGlhRVZaU3doMWVrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZRRWNKYng4My9uYzU4UFd6Z1dvcFZGU0FWcjhka2RoaWhBb29GejNXbCtvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUThzRGRvaDVMQnRkZ1U1VnR5aTVuR29VWWNydnFXNSs2cUZYQXJ6ZGVob2l4SllKSDNvcQo5dFcvREQ2MGw2bjg0aU5wU0tteGhlbVhjbXpQZy9TNjRBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  serviceAccount:
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBemhhRVg5ZnBZdVk4QXoxb2ZKK1NJbWlHaWRzR0phZkRtWFE3L0pZZnlFMEFGLzFKCmZWL2d5TkwxZ0RnSC9NS01CanNFVVIrWU1Yb2xTMHdQRFVhK0lueUkxYUE3aHE1SVN5NDdVWEsxMFNYcmRzRWcKWUNRNEFzVjlHQTJiVUNRbUVyK25FN3JSM3BtVExSMHhiYy9qcGVmSXo4M294b0xveDNSeVRrWkxaRjZhdjNtRgpsQU5wSTN0TFBQSmtDamhhVzRZWWdvTUxLaFl2RVBwZUxGOHZQRmtRWDRRVlI3b1VVUTNHMmMyYmp6ZDcyTVFaCjhVN25BU3E3OWxxaEsyYS9aMzcyTFllSDNnTEhYaFZMa0ZwajBFUXNTWThmTmRwUUloZkdaZmZUMXhOd2xIZGoKVy9OdEZjSlJhL2ZuNENjZFdEZ1I0SC9hM3VGRkdGb0R6VDF1amNUZWJlYjhEMU1jVE1xak9ac2I5TEhlaWNjLwpGaGFPSkFmRzlCTnY3bU8zUEJ6eUV6QUszNmdITmcrMzlnR240UGFySGpGQnNETWh4MXVnbGRTdmVGUjRqRENvCnUrQ2ZCTFBLYVlrdXlFU1JUZXBHVVg3K2ZIdThCZ1l6VkVYTjlRTnorUG0zZGxSNGFyNFo4elQwUVlDSnhKZWMKQzRxWmhidHB6ams1emdQaXA4Y0lTOGVDT3g0KzEzTE1XMmQzdzBqeGFBYXEwS2N5V0U0M3V2eWdjejEvbUNXdQo2QzRYdC9nMjZiY0hxNElCY2YzUHVZTTd6M0JLS2cxVU0yZWp3eGlSRkN2MGRpZ3FpQTBobXhUUUtQTXo0K0czClZxOUg5MVBTdjAwTW1LM3VCMCswK0ZxOHJCVEs5K1EvaE1LUEVGa2pmYThaTU1QbWFoOFFSZ2lKdVFzQ0F3RUEKQVFLQ0FnQUdiWFZiZCtSempUSzU5eVJYSHJMMEY4WjZialpXM2xDZmJKeWlXQnhOcHZrbHhtU1FZSGttU2s0VgozYW1DSEo4NVlvWFQ4ZVJSUnJuN0N6Zzg5Y1BnVjNuOUQ2NUxtUXZ3TEZUMVNWcWFWMUJzdDhGR3ZscHcyNi8zCkhCV0gvbGlocFJDVThQS3l1cDk0Zkx5WjdDM3hjclUwcGZ0b2xaU2xBK0M4eUR4NXVPbWlweXVmWGl2ZFMyOGgKUzM0TFE0NnQ1QlRIblVhdjNWbENja3lWbmJKZmMzZXJRdmRXOFZySTNHRWpVZUpVS1NyWHErWVRQSjYvenBGbQpNWlZ0UVJzZkl6cVNXUFBIM05aUy9OOEtkWWMvYTZEbCttekN4VGhTbCtNOE11cU1mcks0THJFT29SejUzTUdsCldHb0c5N0ZXbXdrVHMya2tJbXFCUSsxeWJVUVJZWWpRcnhWS0x6NHlKeEZueDg1Y21qTnh0bnFhSW9DSzBzbnIKUW1JM2c0UWtzdWlMUkE4RGVRN1lJV0QzOUE0dEx3bDBmWElKeVJVTk1IcXNGUWZ5RFBZbWJpRXF2disvcmhDSgozRThuY1FoZnBuK3U5TmxrRERCRHJOYlVJUTdES3QrMG5zcFY3d2RQMml2cndWQmVXSk5TTHl2SCtEZVRoSElWCk9pdnJEdG9Da2g3cW12RGxJQnREcTNlNkNVeDRNQ1ZwSXgwamlrcVFUZmh5R1RlUkFlb0tmamtIRG1BT09Xd1AKWUlSM0VzK25VY1JnYjUxZGFZbGFYK2hYVXNWUFp1VGZVc0svK2grS3ZLMXR0c21rN1dnTmdyL2ttWTljSndPcQpmK2lzWEQvdUp1dUEwVkpBYWN2WHpranF3b3VpOHoxcWRVV0VUVXFnVnpiWHZ1VmVBUUtDQVFFQTdQWm1OVHFXClBzcHF2ZU1mbmExTHJ3NkpKdGFzWllZQm5EMStWTzQ1ekQybjEyZDMxbzFnQTRaWmdqZmtIVlhiNzE2YnRNM2wKb1M4UTUzN0tiejdFUlcyeEdEMDFMciszSFZZUFB2SFhiTjlyY2d0c2g3T0pHWXhVd1I2OENlT0hTZElSbmhjLwppS0lXSlAxSXBmNzFYZHNQMEtESncyMzlZSXAzck5TT1Jzck9TOTdScWpMU3JSS1MvK25Db215Rll6ZkZwUVUwCkMxdjk3d0F0bStjc3lmNVVhanB2OWErYUFWTjBma1VqNkdLdm8vTExKZGpRY09CN05hdjZMWmFLbU5QcjI4czkKUEtYKzgyem9KV2VZcU92UXdzenhLS3V2OENwanArbW0ycXNCejc0RXREeUh3NFFnUXROZ1d1WkUwS2xvNzlDcQordEhiNDMzTWRkaHZRUUtDQVFFQTNxVWZRTW5Vc1JRV2ZvY2lXdGpSQk0rREpDQXg4ZExkWG1zbERIbHp2NWljCjZEUXFqYzYzUGdOMzFBQW5Ua0xWeU5qWHlrbk9MK2JuMjlvVmxBY2NwbEFSS29GMXBBaU1lK0FTaXp6NDFiYlAKRXAxbnA1ZjlOSTdsTzcvTzJ0MWYvbWhheFhhS3lpMmtFV0FPbVhhWHFqMGpyckEzd2plVzRXOXBEWUVtVjhNQgppd0hQREZicUVmQXRrQVI1bEtMYUlDT3VWdGRna0EwaXNra1Q3c3NJSlBoeVNrczZyTDYyRTZpK1N0Q2J1dGdhCjJLWU1iTEVGSmFSTy8yVXdVZ1R1MUY2eUlNODBUVVROdFAwS2xFK001dmNOUWs4c3U3Z2VnejMxLytyTkkySEkKQmdVREU5U1hDUnFPT0tDZE5VTG91d2VsTVlKd1pJU1NBcEFacXhuaFN3S0NBUUVBMWQ1MTFTanhuZTUzZExiZgpQQ0xDb2xjT05uMmV6MnFwWFdpcTh1Q29UY3lBQmd3ZXZ3aU9WZUFXUFU5UWxhRitoWWJ3SmJtSHZYaUxXMFMyClZMMWp5LzM2enBPL3dsZktYN0hpeEw3bDNoK3dEQmgvZGVMMnBKWmhrSU82MTNvQ0N3Q01ZaEU5aUlZeVVtUkEKQTRJZjF2djJSQ2c2c2lZOWY3cTUxTVZyUEQyakFCczFSTlhtQzhzdDNjZ1BvU1V0SnFXWnZ4ejVJaDkvQ3cwdwpIUHdERXJSM1lBRXFONmFyNnZKMXU5bVBWUmhzeWg1Q2VBQTk4UUxLY1dDc3hpU1BKdXh1ZmN2cmt5ZUcraEdiClhOY3BrNXh5cUw3c0VmY1RMa0l6KzhNSWsyZXdsTjA5eGFhMEtpVEFNVkF5TVJpUGwzeXZkM0x3UHJ6V0ozYk0KNkxmVmdRS0NBUUVBbjlSNzNoL0Z6eVV6akx0bjN6Mjh0eTVjMzJjNVUzZGpzUzlMbG12dHV3Sk15YWtCVDNHeApQQlJ6Umo2aCtOMmo2UjQ1c3g5T3BEYW9CYnpHTnREd01UaFRTbWRMVTJsTHFIWFAraUxZSTF1cnhabzMyaWtTCi9WTURudVB3RkZCTlpDMzMwNzlvblFFc3djaHFVcUsrOTlnU01JcVNUSnRwZGdacnJPVWs2R1cyU3RzT2pyWXEKTEp4MXFPaDllMFY1UHc4K1RWc3FGOTlHSkNTdjZZSFpJK2t5NnNDY3Ezdnc2Nlg4aldxNkVPU29TUlRTNElnbgp3TUQyY1FOc0w4VVl5bDM4ays4TGhkaTVyNDdqdEZwek5TN3ZWc1hOd0NqSnhyK0pSS0dEaUQzZXdPdUNMUTgxCktiVGxtaU03R0F3alZIaUZqMGdyZFExeVgrS2dlcU1HaHdLQ0FRQm1FVXFEdkEydkMzWjFMN2l5WEhMQ3ZKVi8KMkdMSmlBM3VpNmJ3ajBSYnRNM3YydHNWSkZneXIzbzUvQ0J5Y3F4bXpJN25FU1JZMFB0dkN0ZkJ4em56UHdLVQpRdE1KdG1UWmNiVUJ6NWV0ZHJ2OXpCMC9yaXkrcGJYdTdmbjQxV2lZNitlQzRUbURYMTB1NzNpT2pkYngxNTNDCmljaG5zUlV0Q3BBRXg2NDRiSjRla05DbklnTzE4VEF0d3U1eGFSazZybFNlU204emp4V3UzWE5pbnZ0a3MzS2cKd0E4VnFML093OVZtZHcxbnlMajIvTWxyK0lEYmNGaTJCSTRGajhyMkJwYlFXSzNEN2h2bzV4UWhNMnFwSkorQQptb2ltMENyek5ZTkJKdUt4NDUvM2Fqb2lqY3p1R0FtbkYzb3dZR2FEaVEyTTI2K2NISG50bHpLWXlzWHQKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  apiServer:
    image: registry.k8s.io/kube-apiserver:v1.32.2
    certSANs:
      - 192.168.2.101
      - 192.168.2.101
      - 127.0.0.1
    disablePodSecurityPolicy: true
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
        - level: Metadata
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.32.2
    extraArgs:
      bind-address: 0.0.0.0
  proxy:
    disabled: true
    image: registry.k8s.io/kube-proxy:v1.32.2
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.32.2
    extraArgs:
      bind-address: 0.0.0.0
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: false
      service:
        disabled: false
  etcd:
    ca:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNPZ0F3SUJBZ0lRV0ZJRzBUWkU1L1lYMWdiQmp5QmNHakFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkxTURFeU1qSXdNamswTjFvWERUTTFNREV5TURJd01qazBOMW93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkZwNlg0M0pWaGw2CnBPUWJFcUtpVVAwdU5oMmpyUUJ0VHJWWnB0USt4cGxYMXVyd0dHekVkZUcycmFZMmhtcldpRlNoayt5bGMvMk8KVnRvZjNnbTFlQ3VqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVZlJ5cDNoOGtoUkFVCkV2WWUvQVRBNFFhdTNRSXdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTG9oa0ljN0kyc04zNW5QdmJJYUpmdG0KdG5GQkVnTWJVYnh5MEdoZGpxVlBBaUVBeVZtN0lNeWs4Yk5vVW1rVDdMSVdOTGV3cHluVGlXb1J2NmdXdEFCWQpkdkU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZOd3I1NkJOWGhKRnN1cXVURlZFdXhmOE5aTHBURTFwM3hFL3NWcWhRY3ZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFV25wZmpjbFdHWHFrNUJzU29xSlEvUzQySGFPdEFHMU90Vm1tMUQ3R21WZlc2dkFZYk1SMQo0YmF0cGphR2F0YUlWS0dUN0tWei9ZNVcyaC9lQ2JWNEt3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
    advertisedSubnets:
      - 192.168.2.0/24
  coreDNS:
    disabled: true
  allowSchedulingOnControlPlanes: true
