---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-tls-gateway
  namespace: gateway-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: internal-gateway.altena.io
    io.cilium/lb-ipam-ips: 192.168.2.131
spec:
  # Use Cilium as the Gateway implementation
  gatewayClassName: cilium
  listeners:
    - name: https
      # Standard HTTPS port
      port: 443
      # HTTPS protocol for encrypted traffic
      protocol: HTTPS
      # Wildcard hostname to match all subdomains
      hostname: "*.altena.io"
      # TLS configuration
      tls:
        # Terminate TLS at the gateway
        mode: Terminate
        # Reference to the certificate secret
        certificateRefs:
          - kind: Secret
            name: wildcard-altena-io-tls
