---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gatus-rules
spec:
  groups:
    - name: gatus.rules
      rules:
        - alert: GatusEndpointDown
          expr: gatus_results_endpoint_success == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: >-
              {{ $labels.group }}/{{ $labels.name }} is down (gatus)
