---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: system-upgrade-controller
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.2.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-upgrade-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: system-upgrade-controller
  values:
    controllers:
      system-upgrade-controller:
        strategy: RollingUpdate
        replicas: 2
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
        containers:
          app:
            image:
              repository: docker.io/rancher/system-upgrade-controller
              tag: v0.16.3
            env:
              SYSTEM_UPGRADE_CONTROLLER_LEADER_ELECT: true
              SYSTEM_UPGRADE_CONTROLLER_NAME: system-upgrade-controller
              SYSTEM_UPGRADE_CONTROLLER_NAMESPACE:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              SYSTEM_UPGRADE_CONTROLLER_NODE_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              SYSTEM_UPGRADE_JOB_PRIVILEGED: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    rawResources:
      talosServiceAccount:
        apiVersion: talos.dev/v1alpha1
        kind: ServiceAccount
        spec:
          spec:
            roles:
              - os:admin
    rbac:
      bindings:
        system-upgrade-controller:
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - identifier: system-upgrade-controller
    serviceAccount:
      system-upgrade-controller: {}
