---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GF_SECURITY_ADMIN_USER: "{{ .GRAFANA_ADMIN_USERNAME }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: grafana
