apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc

  source:
    path: argo
    repoURL: https://github.com/davealtena/argo-homelab
    targetRevision: HEAD
    # directory:
    #   recurse: true
    #   exclude: '{*/kustomization.yaml}'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true

  # https://docs.cilium.io/en/latest/configuration/argocd-issues/
  ignoreDifferences:
    - kind: ConfigMap
      name: hubble-ca-cert
      jsonPointers:
        - /data/ca.crt
    - kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
