apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
spec:
  description: Security Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: security
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
