---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  storage:
    size: 15Gi
    storageClass: nfs-csi-sc

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB

  bootstrap:
    initdb:
      database: harbor
