---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: development
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: Secret
      name: harbor-postgres-app
      valuesKey: host
      targetPath: database.external.host
    - kind: Secret
      name: harbor-postgres-app
      valuesKey: username
      targetPath: database.external.username
    - kind: Secret
      name: harbor-postgres-app
      valuesKey: password
      targetPath: database.external.password
    - kind: Secret
      name: harbor-postgres-app
      valuesKey: dbname
      targetPath: database.external.coreDatabase
  values:
    updateStrategy:
      type: Recreate
    expose:
      type: clusterIP
    externalURL: https://harbor.altena.io
    redis:
      type: external
      external:
        addr: dragonfly.databases.svc.cluster.local:6379
    database:
      type: external
      external:
        host: harbor-rw.selfhosted.svc.cluster.local:5432
    trivy:
      enabled: true
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry
        jobservice:
          jobLog:
            storageClass: nfs-csi-sc
            size: 1Gi
        database:
          storageClass: nfs-csi-sc
          size: 1Gi
        redis:
          storageClass: nfs-csi-sc
          size: 1Gi
        trivy:
          storageClass: nfs-csi-sc
          size: 5Gi
    cache:
      enabled: true
    existingSecretAdminPassword: harbor
    existingSecretAdminPasswordKey: password
    secretKey:
    existingSecretSecretKey: harbor-encryption
    notary:
      enabled: false
