---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./helm-release.yaml
  - ./pvc.yaml
  - ./route.yaml
