---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-csi-sc
