apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        namespace: databases
        name: cnpg
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
