---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
spec:
  timeout: 15m
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: actual
  values:
    controllers:
      actual:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.10.0
            env:
              ACTUAL_PORT: &httpPort 5006
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

    service:
      app:
        controller: actual
        ports:
          http:
            port: *httpPort

    route:
      app:
        hostnames:
          - finance.${CLUSTER_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: actual
                port: *httpPort

    persistence:
      data:
        existingClaim: actual
        advancedMounts:
          actual:
            app:
              - path: /data
