machine:
  install:
    extraKernelArgs:
      - i915.enable_guc=3
      - intel_iommu=on
      - iommu=pt
  udev:
    rules:
      - # Intel GPU
        SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
  nodeLabels:
    intel.feature.node.kubernetes.io/gpu: "true"
