---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs-system
resources:
  - ./openebs/ks.yaml
components:
  - ../../components/flux/alerts
  - ../../components/namespace
