---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./actual-finance/ks.yaml
  - ./n8n/ks.yaml
  - ./wordpress/ks.yaml
  # - ./nextcloud/ks.yaml
components:
  - ../../components/common
