---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./harbor/ks.yaml
  - ./n8n/ks.yaml
  #- ./nextcloud/ks.yaml
  - ./nocodb/ks.yaml
components:
  - ../../components/common
