apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db
  namespace: selfhosted
spec:
  description: Postgres cluster for the linkding application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 3

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-db-creds

  storage:
    storageClass: openebs-hostpath
    size: 200Mi

  # handy: resources can be used to trigger a redeploy
  resources:
    requests:
      memory: 300Mi

