apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nocodb
spec:
  instances: 1
  storage:
    size: 25Gi
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      search_path: '"$user", public, vectors'

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 300m
    limits:
      memory: 1Gi
