apiVersion: postgresql.cnpg.io/v1
kind: Cluster
# renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
metadata:
  name: nocodb
spec:
  instances: 1
  storage:
    size: 15Gi
    storageClass: nfs-csi-sc

  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3
# renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-pgvecto.rs

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      search_path: '"$user", public, vectors'

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 300m
    limits:
      memory: 1Gi
