---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minimax.yaml
  - ./gpt-4-1.yaml
  - ./gpt-4-1-mini.yaml
  - ./qwen3-14b.yaml
