apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./ingress.yaml
- ./pvc.yaml
- ./svc.yaml

configMapGenerator:
- name: zigbee2mqtt-config
  files:
  - resources/configuration.yaml
