---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt-data
spec:
  storageClassName: nfs-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
