---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: cert-manager-helm-values
    files:
      - helm-values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
