---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns-pihole
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.18.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
  # If you want to use verification, otherwise you can remove this section
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/charts-mirror.*$"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns-pihole
  install:
    disableSchemaValidation: true # Work around schema validation issues
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableSchemaValidation: true # Work around schema validation issues
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    # The rest of your values remain the same
    rbac:
      create: true
      additionalPermissions:
        - apiGroups: [""]
          resources: ["namespaces"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["gateway.networking.k8s.io"]
          resources: ["gateways", "httproutes"]
          verbs: ["get", "watch", "list"]
    policy: sync
    domainFilters:
      - altena.io
    loglevel: info
    serviceMonitor:
      enabled: true
    provider:
      name: pihole
    sources:
      - gateway-httproute
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://192.168.1.111
      - name: &secret EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: *secret
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      - --pihole-tls-skip-verify
    securityContext:
      fsGroup: 65534
