---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    rbac:
      create: true
      additionalPermissions:
        - apiGroups: [""]
          resources: ["namespaces"]
          verbs: ["get","watch","list"]
        - apiGroups: ["gateway.networking.k8s.io"]
          resources: ["gateways","httproutes"]
          verbs: ["get","watch","list"]
    policy: sync
    domainFilters:
      - altena.io
    loglevel: info
    serviceMonitor:
      enabled: true
    provider:
      name: pihole
    sources:
      - gateway-httproute
      - service
      - ingress
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://192.168.2.111
      - name: &secret EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: *secret
    extraArgs:
      - --gateway-namespace=gateway-system
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --events
      - --ignore-ingress-tls-spec
      - --ingress-class=internal
      - --pihole-tls-skip-verify #TODO: Fix when TLS is configured on pi-hole
    securityContext:
      fsGroup: 65534
