---
originRequest:
  originServerName: external.altena.io

ingress:
  - hostname: altena.io
    service: &svc https://envoy-external.{{ .Release.Namespace }}.svc.cluster.local
  - hostname: "*.altena.io"
    service: *svc
  - service: http_status:404
