---
originRequest:
  originServerName: external.altena.io

ingress:
  - hostname: altena.io
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.altena.io"
    service: *svc
  - service: http_status:404
