---
originRequest:
  originServerName: ${CLUSTER_DOMAIN}

ingress:
  - hostname: ${CLUSTER_DOMAIN}
    service: &svc https://envoy-external.network.svc.cluster.local
  - hostname: "*.${CLUSTER_DOMAIN}"
    service: *svc
  - service: http_status:404
