apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-operator
subjects:
- kind: ServiceAccount
  name: security-operator
  namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: security-operator
  apiGroup: rbac.authorization.k8s.io
