apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-operator
  namespace: security-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-operator
subjects:
- kind: ServiceAccount
  name: security-operator
  namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: security-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-operator
  namespace: security-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-operator
  template:
    metadata:
      labels:
        app: security-operator
    spec:
      serviceAccountName: security-operator
      containers:
      - name: operator
        image: harbor.altena.io/prlx-eu/agent:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
