apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: security-operator
    spec:
      serviceAccountName: security-operator
      containers:
      - name: operator
        image: harbor.altena.io/prlx-eu/agent:latest
        imagePullPolicy: Always
        args:
        - --scan-interval=5m
        - --scanners=rbac,network,orphaned,securitycontext
        - --log-level=info
        - --log-format=json
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: security-operator-config
              key: backend-url
        - name: BACKEND_TOKEN
          valueFrom:
            secretKeyRef:
              name: security-operator-secrets
              key: backend-token
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: security-operator-secrets
              key: jwt-secret
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
