apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: security-operator
  app.kubernetes.io/part-of: prlx-security
  app.kubernetes.io/component: operator
