apiVersion: v1
kind: Service
metadata:
  name: security-operator
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  - name: health
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: security-operator
