apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prlx-db
spec:
  instances: 1
  imageName: ghcr.io/clevyr/cloudnativepg-timescale:16-ts2

  postgresql:
    parameters:
      shared_buffers: "256MB"
    shared_preload_libraries:
      - timescaledb

  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;

  storage:
    size: 20Gi
    storageClass: nfs-csi-sc

  walStorage:
    size: 5Gi
    storageClass: nfs-csi-sc

  monitoring:
    enablePodMonitor: true
