---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prlx-db
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: official-timescaledb-image
    major: 14
  imagePullPolicy: IfNotPresent
  postgresUID: 70
  postgresGID: 70

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  storage:
    size: 10Gi
    storageClass: nfs-csi-sc

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      timescaledb.max_background_workers: "8"
      timescaledb.max_parallel_workers: "4"
      timescaledb.max_parallel_workers_per_gather: "4"

  monitoring:
    enablePodMonitor: true

  walStorage:
    storageClass: nfs-csi-sc
    size: 5Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: ImageCatalog
metadata:
  name: official-timescaledb-image
spec:
  images:
    - major: 14
      image: timescale/timescaledb-ha:pg14.18-ts2.19.3-oss
