---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name prlx-backend
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        jwt-secret: |-
          {{ .jwt_secret }}
  refreshInterval: 15m
  dataFrom:
    - extract:
        key: *name
