---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: unifi-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.19.0
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: unifi-dns
  install:
    remediation:
      retries: -1
  values:
    fullnameOverride: &name external-dns-unifi
    logLevel: &logLevel info
    domainFilters:
      - altena.io
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-unifi-secret
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.6.2
        env:
          - name: LOG_LEVEL
            value: *logLevel
          - name: UNIFI_HOST
            value: https://192.168.1.1
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi-secret
                key: external_dns_api_key
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M
    serviceMonitor:
      enabled: true
    sources:
      - gateway-httproute
      - service
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
