apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: cluster
  source:
    repoURL: https://github.com/davealtena/argo-homelab
    path: apps/kube-system/cilium
    targetRevision: main
  destination:
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
  # info:
  #   - name: "Github Repository:"
  #     value: >-
  #       https://github.com/kubernetes/ingress-nginx
  #   - name: "Official documentation:"
  #     value: >-
  #       https://kubernetes.github.io/ingress-nginx/
  #   - name: "Github Helm chart:"
  #     value: >-
  #       https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
