---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    updateStrategy:
      type: Recreate
    expose:
      type: clusterIP
      tls:
        enabled: false
    externalURL: https://harbor.${CLUSTER_DOMAIN}
    database:
      type: external
    trivy:
      enabled: true
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry
        jobservice:
          jobLog:
            storageClass: nfs-csi-sc
            size: 1Gi
        database:
          storageClass: nfs-csi-sc
          size: 1Gi
        redis:
          storageClass: nfs-csi-sc
          size: 1Gi
        trivy:
          storageClass: nfs-csi-sc
          size: 5Gi
    cache:
      enabled: true
    existingSecretAdminPassword: harbor
    existingSecretAdminPasswordKey: password
    secretKey:
    existingSecretSecretKey: harbor-encryption
    notary:
      enabled: false
