---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-git-sync
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-git-sync
    creationPolicy: Owner
    template:
      data:
        FORGEJO_TOKEN: "{{ .forgejo_hass_sync_token }}"
        HASS_TOKEN: "{{ .hass_api_token }}"
  dataFrom:
    - extract:
        key: forgejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "forgejo_$1"
    - extract:
        key: homeassistant
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hass_$1"
