# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.2

clusterName: "valhalla"
endpoint: https://192.168.2.101:6443
clusterPodNets:
  - "10.69.0.0/16"
clusterSvcNets:
  - "10.96.0.0/16"
additionalApiServerCertSans: &sans
  - "192.168.2.101"
  - 127.0.0.1 # KubePrism
additionalMachineCertSans: *sans

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "odin"
    ipAddress: "192.168.2.102"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:fd:a1:37"
        dhcp: false
        addresses:
          - "192.168.2.102/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.2.254"
        mtu: 1500
        vip:
          ip: "192.168.2.101"
  - hostname: "thor"
    ipAddress: "192.168.2.103"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:af:e9:a4"
        dhcp: false
        addresses:
          - "192.168.2.103/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.2.254"
        mtu: 1500
        vip:
          ip: "192.168.2.101"
  - hostname: "frigg"
    ipAddress: "192.168.2.104"
    installDisk: "/dev/sda"
    talosImageURL: factory.talos.dev/installer/d3dc673627e9b94c6cd4122289aa52c2484cddb31017ae21b75309846e257d30
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:15:57:6f"
        dhcp: false
        addresses:
          - "192.168.2.104/24"
        routes:
          - network: 0.0.0.0/0
            gateway: "192.168.2.254"
        mtu: 1500
        vip:
          ip: "192.168.2.101"

# Global patches
patches:
  - # Force nameserver
    |-
    machine:
      network:
        nameservers:
          - 192.168.2.111
  - # Configure NTP
    |-
    machine:
      time:
        disabled: false
        servers:
          - time.cloudflare.com
  - "@./patches/global/cluster-discovery.yaml"
  - "@./patches/global/containerd.yaml"
  - "@./patches/global/disable-search-domain.yaml"
  - "@./patches/global/hostdns.yaml"
  - "@./patches/global/kubelet.yaml"
  - "@./patches/global/openebs-local.yaml"
  - "@./patches/global/sysctl.yaml"
  - "@./patches/global/intel-gpu.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/api-access.yaml"
    - "@./patches/controller/cluster.yaml"
    - "@./patches/controller/disable-admission-controller.yaml"
    - "@./patches/controller/etcd.yaml"
