---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-github
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: toolhive-github
    creationPolicy: Owner
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .GITHUB_PERSONAL_ACCESS_TOKEN }}"
  dataFrom:
    - extract:
        key: toolhive
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-garmin
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: toolhive-garmin
    creationPolicy: Owner
    template:
      data:
        GARMIN_EMAIL: "{{ .GARMIN_EMAIL }}"
        GARMIN_PASSWORD: "{{ .GARMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: toolhive
