---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: garmin-connect-mcp
spec:
  image: docker.io/node:24-alpine
  transport: stdio
  args: ["npx", "@nicolasvegam/garmin-connect-mcp@1.1.1"]
  groupRef:
    name: mcp-tools
  secrets:
    - name: toolhive-garmin-email
      key: GARMIN_EMAIL
    - name: toolhive-garmin-password
      key: GARMIN_PASSWORD
