---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: hass-mcp
spec:
  image: docker.io/voska/hass-mcp:0.5.0
  transport: stdio
  proxyMode: streamable-http
  proxyPort: 8080
  env:
    - name: HA_URL
      value: http://home-assistant.home-automation.svc.cluster.local:8123
  secrets:
    - name: toolhive-hass
      key: HA_TOKEN
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  groupRef:
    name: mcp-tools
