---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: depName=k8snetworkplumbingwg/network-attachment-definition-client datasource=github-releases
  - ./crds.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
