---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
# renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
metadata:
  name: n8n
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  storage:
    size: 2Gi
    storageClass: nfs-csi-sc

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 128MB

  bootstrap:
    initdb:
      database: n8n
