---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: k8s-content-engine
spec:
  instances: 1  # Single instance is fine for this workload
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi  # 5GB is plenty for content data
    storageClass: nfs-csi-sc

  postgresql:
    parameters:
      max_connections: "50"  # Low connections needed
      shared_buffers: 128MB
      work_mem: "4MB"

  bootstrap:
    initdb:
      database: k8s_content
      owner: n8n
      postInitSQL:
        - CREATE TABLE IF NOT EXISTS k8s_content_raw (
            id SERIAL PRIMARY KEY,
            title TEXT NOT NULL,
            link TEXT UNIQUE NOT NULL,
            description TEXT,
            pub_date TIMESTAMP,
            source TEXT,
            source_type TEXT,
            collected_at TIMESTAMP DEFAULT NOW(),
            analyzed BOOLEAN DEFAULT FALSE,
            final_score DECIMAL(3,1),
            passed_validation BOOLEAN,
            analysis_data JSONB,
            analyzed_at TIMESTAMP
          );
        - CREATE INDEX idx_analyzed ON k8s_content_raw(analyzed);
        - CREATE INDEX idx_passed ON k8s_content_raw(passed_validation);
        - CREATE INDEX idx_score ON k8s_content_raw(final_score);
        - CREATE TABLE IF NOT EXISTS k8s_content_approved (
            id SERIAL PRIMARY KEY,
            raw_content_id INTEGER REFERENCES k8s_content_raw(id),
            content_type TEXT,
            generated_content TEXT,
            best_time TIMESTAMP,
            status TEXT DEFAULT 'pending',
            approved_at TIMESTAMP,
            posted_at TIMESTAMP,
            engagement_stats JSONB
          );
        - CREATE TABLE IF NOT EXISTS k8s_competitor_posts (
            id SERIAL PRIMARY KEY,
            competitor TEXT,
            title TEXT,
            link TEXT UNIQUE,
            posted_date TIMESTAMP,
            themes TEXT[],
            collected_at TIMESTAMP DEFAULT NOW()
          );
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO n8n;
        - GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO n8n;

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 256Mi
