---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./cluster.yaml
  - ./content-engine-cluster.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./pvc.yaml
