apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TIMEZONE: ENC[AES256_GCM,data:RW5PSTqext77nVOEzpxSVw==,iv:kDTTV3b9/lRegF+cTCfqTY3J7CR0BG1cuI6kGTIERBw=,tag:hKZu1sIwwyf91yn3bKnyGg==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:MV4nGk9PJX02,iv:BZd+GrDvYrkfx7/ni2pCdXkDaMv56O0XrT8Th6GB+iM=,tag:AmQhf9jVdvoTEb9qj9Q3Xw==,type:str]
sops:
    age:
        - recipient: age1yrzd67uvapjjawwjgfc7drkyu8pk2m800w4knjzrg69jxkm0afcqnr9qfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRnBVSEdyOTNITCsvY1RR
            eWcvdFFpTUFaR2x2cEF5LytmT2x4VWczOXpNCmRsUUFNN09vbjlSdmdqaWd1dzdn
            RVVLNCtiUzdyL0hiNWZVLzRJUnk0UmMKLS0tIFA1VGFTYmlaS3JWZ0R4Z3ZjODE3
            dzc3OFBmUnF0M2JGRFBQNGZqTG5UQncKqq79+DMDRktQu1lh7TJJL0keiFnv1T/2
            TNNmFmAExO5uJWvMmANDTvOXkTmCWpEtYl6XY+bAwnFSSC6i58z1zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-30T19:07:52Z"
    mac: ENC[AES256_GCM,data:gDPOuNrOrMs/QcZq7NNUz7JIz9socoFcRCH/vCejM6NPnEgccD1D7p0aSH7//FI/8DCzENzhBnF7oKMz821jQyYNPBCZ8GQxr6970uasjKNrC1wErE/44Zdyfq+cAfZuTtsz9uOoK9OQQ0RAnHEwlzx7YCIazgb5qLzdnTlLkeM=,iv:XOJeCsRRduo9ZPaVki+brR2ACmUo7znQ+aVShFpuZdw=,tag:tLrc4g0+SvsKnuR7JJt9Ng==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
