---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app booklore
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: cnpg-cluster
    - name: volsync
    - name: rook-ceph-cluster
  interval: 1h
  path: kubernetes/apps/media/booklore/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: booklore
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool
