apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.16.0
    releaseName: onepassword-connect
    namespace: external-secrets
    valuesInline:
      controllers:
        onepassword-connect:
          strategy: RollingUpdate
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            api:
              image:
                repository: docker.io/1password/connect-api
                tag: 1.7.3@sha256:0601c7614e102eada268dbda6ba4b5886ce77713be2c332ec6a2fd0f028484ba
              env:
                OP_HTTP_PORT: 80
                OP_BUS_PORT: 11220
                OP_BUS_PEERS: localhost:11221
                OP_SESSION:
                  valueFrom:
                    secretKeyRef:
                      name: onepassword-connect-secret
                      key: 1password-credentials.json
