apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.16.0
    releaseName: onepassword-connect
    namespace: external-secrets
    valuesInline:
      controllers:
        onepassword-connect:
          strategy: RollingUpdate
          annotations:
            reloader.stakater.com/auto: "true"
          containers:
            api:
              image:
                repository: docker.io/1password/connect-api
                tag: 1.7.3@sha256:0601c7614e102eada268dbda6ba4b5886ce77713be2c332ec6a2fd0f028484ba
              env:
                XDG_DATA_HOME: &configDir /config
                OP_HTTP_PORT: &apiPort 8080
                OP_BUS_PORT: 11220
                OP_BUS_PEERS: localhost:11221
                OP_SESSION:
                  valueFrom:
                    secretKeyRef:
                      name: onepassword-connect-secret
                      key: 1password-credentials.json
            sync:
              image:
                repository: docker.io/1password/connect-sync
                tag: 1.7.3@sha256:2f17621c7eb27bbcb1f86bbc5e5a5198bf54ac3b9c2ffac38064d03c932b07d5
              env:
                XDG_DATA_HOME: *configDir
                OP_HTTP_PORT: &syncPort 8081
                OP_BUS_PORT: 11221
                OP_BUS_PEERS: localhost:11220
                OP_SESSION:
                  valueFrom:
                    secretKeyRef:
                      name: onepassword-connect-secret
                      key: 1password-credentials.json
