---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  storageClassName: nfs-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
