apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: forgejo
  namespace: selfhosted
spec:
  interval: 1h
  url: oci://code.forgejo.org/forgejo-helm/forgejo
  ref:
    tag: "12.3.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: forgejo
    namespace: selfhosted
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
      create: false
      claimName: forgejo
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: false
    gitea:
      admin:
        username: forgejo-admin
        email: forgejo@altena.io
      config:
        APP_NAME: "forgejo"
        security:
          PASSWORD_COMPLEXITY: spec
        database:
          DB_TYPE: postgres
          SCHEMA: public
        service:
          REQUIRE_SIGNIN_VIEW: true
          DISABLE_REGISTRATION: true
          ENABLE_NOTIFY_MAIL: false
        openid:
          ENABLE_OPENID_SIGNIN: false
        oauth2:
          ENABLE_AUTO_REGISTRATION: true
          USERNAME: nickname
          UPDATE_AVATAR: true
          ACCOUNT_LINKING: auto
        mailer:
          ENABLED: false
  valuesFrom:
    - kind: Secret
      name: forgejo-postgres-rw
      valuesKey: host
      targetPath: gitea.config.database.HOST
    - kind: Secret
      name: forgejo-postgres-rw
      valuesKey: dbname
      targetPath: gitea.config.database.NAME
    - kind: Secret
      name: forgejo-postgres-rw
      valuesKey: user
      targetPath: gitea.config.database.USER
    - kind: Secret
      name: forgejo-postgres-rw
      valuesKey: password
      targetPath: gitea.config.database.PASSWD
