apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo
  namespace: selfhosted
spec:
  interval: 5m
  chart:
    spec:
      chart: forgejo
      version: "12.0.0"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: flux-system
      interval: 5m

  values:
    ingress:
      enabled: false

    persistence:
      enabled: true
      create: false
      claimName: forgejo

    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: false

    gitea:
      admin:
        username: forgejo-admin
        email: forgejo@altena.io

      config:
        APP_NAME: "forgejo"
        security:
          PASSWORD_COMPLEXITY: spec
        # database:
        #   DB_TYPE: postgres
        #   HOST: <mysql HOST>
        #   NAME: gitea
        #   USER: root
        #   PASSWD: gitea
        #   SCHEMA: gitea
        service:
          REQUIRE_SIGNIN_VIEW: true
          DISABLE_REGISTRATION: true
          ENABLE_NOTIFY_MAIL: false
        openid:
          ENABLE_OPENID_SIGNIN: false
        oauth2:
          ENABLE_AUTO_REGISTRATION: true
          USERNAME: nickname
          UPDATE_AVATAR: true
          ACCOUNT_LINKING: auto
        mailer:
          ENABLED: false

