apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm #TODO: Template
    chart: "argo-cd"
    targetRevision: 7.3.4
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
      - $values/argocd/values.yaml
      # - $values/bootstrap/eks/prod/values-notifications.yaml
  - repoURL: https://github.com/davealtena/argo-homelab #TODO: Template
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
