apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/projects

- base/core/argocd.yaml

- base/argocd.yaml
- base/app-of-apps.yaml
- base/namespace.yaml
- base/github-deploy-key.yaml

# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
helmCharts:
# https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
- name: argo-cd
  version: 7.4.7
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  namespace: argocd
