apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- base/projects

- base/core/argocd.yaml
- base/core/networking.yaml


- base/repo-role.yaml
- base/svc-monitors.yaml
- github.com/argoproj-labs/argocd-extension-metrics/manifests?ref=v1.0.3
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.3/manifests/install.yaml

namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newTag: v2.13.0
patches:
- patch: |-
    - op: replace
      path: "/metadata/namespace"
      value: "monitoring"
  target:
    kind: ServiceMonitor
- patch: |-
    - op: add
      path: "/spec/strategy"
      value:
        type: "Recreate"
    - op: replace
      path: "/spec/template/spec/serviceAccountName"
      value: "argocd-server"
  target:
    kind: Deployment
    name: argocd-server
